// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceBHelloClient is the client API for ServiceBHello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceBHelloClient interface {
	SayHello(ctx context.Context, in *ServiceBHelloRequest, opts ...grpc.CallOption) (*ServiceBHelloResponse, error)
}

type serviceBHelloClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceBHelloClient(cc grpc.ClientConnInterface) ServiceBHelloClient {
	return &serviceBHelloClient{cc}
}

func (c *serviceBHelloClient) SayHello(ctx context.Context, in *ServiceBHelloRequest, opts ...grpc.CallOption) (*ServiceBHelloResponse, error) {
	out := new(ServiceBHelloResponse)
	err := c.cc.Invoke(ctx, "/serviceb.ServiceBHello/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceBHelloServer is the server API for ServiceBHello service.
// All implementations must embed UnimplementedServiceBHelloServer
// for forward compatibility
type ServiceBHelloServer interface {
	SayHello(context.Context, *ServiceBHelloRequest) (*ServiceBHelloResponse, error)
	mustEmbedUnimplementedServiceBHelloServer()
}

// UnimplementedServiceBHelloServer must be embedded to have forward compatible implementations.
type UnimplementedServiceBHelloServer struct {
}

func (UnimplementedServiceBHelloServer) SayHello(context.Context, *ServiceBHelloRequest) (*ServiceBHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedServiceBHelloServer) mustEmbedUnimplementedServiceBHelloServer() {}

// UnsafeServiceBHelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceBHelloServer will
// result in compilation errors.
type UnsafeServiceBHelloServer interface {
	mustEmbedUnimplementedServiceBHelloServer()
}

func RegisterServiceBHelloServer(s grpc.ServiceRegistrar, srv ServiceBHelloServer) {
	s.RegisterService(&ServiceBHello_ServiceDesc, srv)
}

func _ServiceBHello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceBHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceBHelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serviceb.ServiceBHello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceBHelloServer).SayHello(ctx, req.(*ServiceBHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceBHello_ServiceDesc is the grpc.ServiceDesc for ServiceBHello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceBHello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serviceb.ServiceBHello",
	HandlerType: (*ServiceBHelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ServiceBHello_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/service_b.proto",
}
